### ISSUE TITLE
关于geodata数据库

### ISSUE THREAD

**Issue by cyysu** [ContrapunctusXIV/WeAnalyse#2]
你好，非常感谢你提供了如此的开源程序，目前在看你的程序。但我发现缺少一些文件，比如geo分析的时候那个地区库，geodata/data.sqlite

另外就是关于Expert Mode这个怎么使用可以做个解释吗？或者方便给个联系方式吗？

**Comment by ContrapunctusXIV** [comment]
expert mode是先把微信数据导入到mysql再进行处理的，效率更高，但我还没写好…
geo是地理位置分析，根据聊天中提到的地区在地图上标记出来，但效果不好，就先撂在那里了。
